#!/bin/bash
# This script creates a new bash script, sets permissions and more

if [[ ! $1 ]]; then
  echo "Missing argument"
  exit 1
fi

scriptname="$1"
dir="${HOME}/bin"
filename="${dir}/${scriptname}"

if [[ -e $filename ]]; then
  echo "File ${filename} already exists"
  exit 1
fi

if type "$scriptname" > /dev/null 2>&1; then
  echo "There is already a command with name ${scriptname}"
  exit 1
fi

if [[ ! -d $dir ]]; then
  if mkdir "$dir"; then
    echo "created ${dir}"
  else
    echo "Could not create ${dir}."
    exit 1
  fi
fi

echo '#!/bin/bash -x' > "$filename"
chmod u+x "$filename"

if [[ $EDITOR ]]; then
  $EDITOR "$filename"
else
  echo "Script created; not starting editor because \$EDITOR is not set."
fi
